import type { FeedPost } from './types';

// Seed feed so the demo is never empty. These double as the records we insert into
// DynamoDB via the seed script once the backend is live (see PLAN.md, Phase 3).
export const SEED_POSTS: FeedPost[] = [
  {
    id: 'seed-1',
    title: 'Building a developer feed with AWS Amplify Gen 2',
    url: 'https://docs.amplify.aws/react/build-a-backend/data/',
    tag: 'aws',
    previewImage: 'https://picsum.photos/seed/amplify/640/360',
    previewDescription: 'Model your data, set authorization rules, and connect a frontend in TypeScript.',
    authorUsername: 'amplify_dev',
    createdAt: '2026-06-20T09:00:00.000Z',
    likeCount: 42,
    commentCount: 5,
  },
  {
    id: 'seed-2',
    title: 'Rust is eating the systems world — here is why',
    url: 'https://blog.rust-lang.org/',
    tag: 'rust',
    previewImage: 'https://picsum.photos/seed/rust/640/360',
    previewDescription: 'Memory safety without a garbage collector keeps winning over teams.',
    authorUsername: 'ferris',
    createdAt: '2026-06-20T08:30:00.000Z',
    likeCount: 128,
    commentCount: 17,
  },
  {
    id: 'seed-3',
    title: 'shadcn/ui: components you copy into your codebase',
    url: 'https://ui.shadcn.com/',
    tag: 'frontend',
    previewImage: 'https://picsum.photos/seed/shadcn/640/360',
    previewDescription: 'Beautifully designed components built with Radix UI and Tailwind CSS.',
    authorUsername: 'design_sys',
    createdAt: '2026-06-20T08:00:00.000Z',
    likeCount: 75,
    commentCount: 9,
  },
  {
    id: 'seed-4',
    title: 'Next.js 16: what actually changed',
    url: 'https://nextjs.org/blog',
    tag: 'nextjs',
    previewImage: 'https://picsum.photos/seed/nextjs/640/360',
    previewDescription: 'Turbopack by default, faster builds, and refreshed routing internals.',
    authorUsername: 'vercel_fan',
    createdAt: '2026-06-20T07:30:00.000Z',
    likeCount: 96,
    commentCount: 12,
  },
  {
    id: 'seed-5',
    title: 'A practical guide to Postgres indexes',
    url: 'https://www.postgresql.org/docs/current/indexes.html',
    tag: 'databases',
    previewImage: 'https://picsum.photos/seed/postgres/640/360',
    previewDescription: 'B-tree, GIN, GiST — when each one earns its keep.',
    authorUsername: 'sql_sam',
    createdAt: '2026-06-20T07:00:00.000Z',
    likeCount: 54,
    commentCount: 6,
  },
  {
    id: 'seed-6',
    title: 'Show HN: I built a CLI that explains your stack traces',
    url: 'https://github.com/trending',
    tag: 'tools',
    previewImage: 'https://picsum.photos/seed/cli/640/360',
    previewDescription: 'Paste a trace, get a plain-English root cause and a suggested fix.',
    authorUsername: 'cli_wizard',
    createdAt: '2026-06-20T06:30:00.000Z',
    likeCount: 210,
    commentCount: 31,
  },
  {
    id: 'seed-7',
    title: 'The case for typed APIs end-to-end',
    url: 'https://trpc.io/',
    tag: 'typescript',
    previewImage: 'https://picsum.photos/seed/trpc/640/360',
    previewDescription: 'Move fast and never ship a contract mismatch again.',
    authorUsername: 'ts_tina',
    createdAt: '2026-06-20T06:00:00.000Z',
    likeCount: 67,
    commentCount: 8,
  },
  {
    id: 'seed-8',
    title: 'How we cut our Docker image from 1.2GB to 80MB',
    url: 'https://docs.docker.com/build/building/best-practices/',
    tag: 'devops',
    previewImage: 'https://picsum.photos/seed/docker/640/360',
    previewDescription: 'Multi-stage builds, distroless bases, and ruthless layer hygiene.',
    authorUsername: 'ops_olly',
    createdAt: '2026-06-20T05:30:00.000Z',
    likeCount: 89,
    commentCount: 14,
  },
];
